<?php return [
    'path' => 'iblock/sber_partners/properties/IS_FEDERAL',
    'init' => [
        'iblock' => 'sber_partners',
        'property' => 'IS_FEDERAL',
    ],
    'commit' => '540eb20a917d2ce95b0770b7519dcab8',
    'entity' => 'DbVersion\\EntityTypes\\Iblock\\Property\\Prop\\BasicL',
    'module' => 'iblock',
    'data' => [
        'IBLOCK_ID' => 'sber_partners',
        'NAME' => 'Федеральный',
        'ACTIVE' => 'Y',
        'SORT' => '500',
        'CODE' => 'IS_FEDERAL',
        'DEFAULT_VALUE' => '',
        'PROPERTY_TYPE' => 'L',
        'ROW_COUNT' => '1',
        'COL_COUNT' => '30',
        'LIST_TYPE' => 'C',
        'MULTIPLE' => 'N',
        'XML_ID' => null,
        'FILE_TYPE' => '',
        'MULTIPLE_CNT' => '5',
        'LINK_IBLOCK_ID' => '0',
        'WITH_DESCRIPTION' => 'N',
        'SEARCHABLE' => 'N',
        'FILTRABLE' => 'N',
        'IS_REQUIRED' => 'N',
        'USER_TYPE' => null,
        'USER_TYPE_SETTINGS_LIST' => true,
        'USER_TYPE_SETTINGS' => true,
        'HINT' => '',
    ],
    'dependencies' => [
        0 => 'iblock/sber_partners/install',
    ],
    'additional' => [
        0 => 'iblock/sber_partners/properties/IS_FEDERAL_enum',
    ],
];