<?php return [
    'path' => 'iblock/sber_partners/install',
    'init' => [
        'iblock' => 'sber_partners',
    ],
    'commit' => '8e9d2c7ff10363f5459daf9875e2710e',
    'entity' => 'DbVersion\\EntityTypes\\Iblock\\Iblock',
    'module' => 'iblock',
    'data' => [
        'IBLOCK_TYPE_ID' => 'partnersoffers',
        'LID' => 's1',
        'CODE' => 'sber_partners',
        'NAME' => 'Партнёры',
        'ACTIVE' => 'Y',
        'SORT' => '500',
        'LIST_PAGE_URL' => '#SITE_DIR#/partners/',
        'DETAIL_PAGE_URL' => '#SITE_DIR#/partners/#ELEMENT_ID#/',
        'SECTION_PAGE_URL' => '#SITE_DIR#/partnersoffers/list.php?SECTION_ID=#SECTION_ID#',
        'CANONICAL_PAGE_URL' => '',
        'PICTURE' => null,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'XML_ID' => null,
        'INDEX_ELEMENT' => 'Y',
        'INDEX_SECTION' => 'Y',
        'WORKFLOW' => 'N',
        'BIZPROC' => 'N',
        'SECTION_CHOOSER' => 'L',
        'LIST_MODE' => '',
        'RIGHTS_MODE' => 'S',
        'SECTION_PROPERTY' => 'Y',
        'PROPERTY_INDEX' => null,
        'LAST_CONV_ELEMENT' => '0',
        'EDIT_FILE_BEFORE' => '',
        'EDIT_FILE_AFTER' => '',
        'GROUP_ID' => [
            1 => 'X',
        ],
    ],
    'dependencies' => [
        0 => 'iblocktype/partnersoffers',
        1 => 'user/group/1',
    ],
    'additional' => [
        0 => 'iblock/sber_partners/properties/IS_FEDERAL',
        1 => 'iblock/sber_partners/properties/IS_POPULAR',
        2 => 'iblock/sber_partners/properties/IS_ONLINE',
    ],
];