<?php return [
    'path' => 'iblock/sber_partners_addresses/properties/CITY',
    'init' => [
        'iblock' => 'sber_partners_addresses',
        'property' => 'CITY',
    ],
    'commit' => '4ccf903389dda3601367697ea84413be',
    'entity' => 'DbVersion\\EntityTypes\\Iblock\\Property\\Prop\\BasicS',
    'module' => 'iblock',
    'data' => [
        'IBLOCK_ID' => 'sber_partners_addresses',
        'NAME' => 'Город',
        'ACTIVE' => 'Y',
        'SORT' => '500',
        'CODE' => 'CITY',
        'DEFAULT_VALUE' => '',
        'PROPERTY_TYPE' => 'S',
        'ROW_COUNT' => '1',
        'COL_COUNT' => '30',
        'LIST_TYPE' => 'L',
        'MULTIPLE' => 'N',
        'XML_ID' => null,
        'FILE_TYPE' => '',
        'MULTIPLE_CNT' => '5',
        'LINK_IBLOCK_ID' => '0',
        'WITH_DESCRIPTION' => 'N',
        'SEARCHABLE' => 'N',
        'FILTRABLE' => 'N',
        'IS_REQUIRED' => 'N',
        'USER_TYPE' => null,
        'USER_TYPE_SETTINGS_LIST' => true,
        'USER_TYPE_SETTINGS' => true,
        'HINT' => '',
    ],
    'dependencies' => [
        0 => 'iblock/sber_partners_addresses/install',
    ],
    'additional' => [],
];