<?php return [
    'path' => 'iblock/sber_partners_addresses/properties/PARTNER',
    'init' => [
        'iblock' => 'sber_partners_addresses',
        'property' => 'PARTNER',
    ],
    'commit' => '2788887d203be159dc5fdaa8379e5bf3',
    'entity' => 'DbVersion\\EntityTypes\\Iblock\\Property\\Prop\\BasicE',
    'module' => 'iblock',
    'data' => [
        'IBLOCK_ID' => 'sber_partners_addresses',
        'NAME' => 'Партнёр',
        'ACTIVE' => 'Y',
        'SORT' => '500',
        'CODE' => 'PARTNER',
        'DEFAULT_VALUE' => '',
        'PROPERTY_TYPE' => 'E',
        'ROW_COUNT' => '1',
        'COL_COUNT' => '30',
        'LIST_TYPE' => 'L',
        'MULTIPLE' => 'N',
        'XML_ID' => null,
        'FILE_TYPE' => '',
        'MULTIPLE_CNT' => '5',
        'LINK_IBLOCK_ID' => 'sber_partners',
        'WITH_DESCRIPTION' => 'N',
        'SEARCHABLE' => 'N',
        'FILTRABLE' => 'N',
        'IS_REQUIRED' => 'Y',
        'USER_TYPE' => null,
        'USER_TYPE_SETTINGS_LIST' => true,
        'USER_TYPE_SETTINGS' => true,
        'HINT' => '',
    ],
    'dependencies' => [
        0 => 'iblock/sber_partners_addresses/install',
        1 => 'iblock/sber_partners/install',
    ],
    'additional' => [],
];